[server]
maxUploadSize = 50
headless = true
address = "127.0.0.1"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#087f8c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f5f7"
textColor = "#192b3a"
